#!/usr/bin/env python3
"""P1 - frequency-weighted CPI.

Reweights CPI leaf items by *purchase frequency* (CE Diary Survey: weighted purchase
entries per consumer-unit-week) instead of expenditure share, then builds a
December-chained Laspeyres index exactly like the P0 replica so the two are comparable.

  p1_salience.py [--years=22,23,24] [--no-boot] [--no-extend] [--force-extend]

  --years         diary years to load (2-digit).            default 22,23,24
  --no-boot       skip the 44-replicate BRR bootstrap.
  --no-extend     do not try to back-fill Dec-2017..2019 CPI relative-importance weights.
  --force-extend  re-parse and re-load the archived 2017-2019 weights even if present.

Naming: the *user-facing* label for this method is "frequency-weighted". The historical
table and column names ('salience', p1_item_salience.w_sal, scheme 'salience', 'blend50')
are kept unchanged because other pipelines read them.

Schemes written to p1_index
  official_replica  December relative importance (= P0 replica of the published CPI-U NSA)
  salience          purchase-entry frequency weights                 [label: frequency-weighted]
  blend50           0.5 * official_replica + 0.5 * salience
  bill_salience     frequency weights with a monthly-bill floor      [label: bill-adjusted frequency]
  bill_blend50      0.5 * official_replica + 0.5 * bill_salience

Tables
  p1_ucc_freq(diary_year, ucc, entries_per_cuweek, spend_per_cuweek, share_buying)
  p1_item_salience(diary_year, item_code, freq, w_sal, w_exp)
  p1_index(scheme, ym, idx, yoy)
  p1_sensitivity(variant, ym, yoy)          -- robustness variants of the frequency index
  p1_boot(scheme, ym, yoy, se)              -- se = BRR standard error of (scheme YoY - official replica YoY)

out/p1_salience.json schema
  generated_at        ISO-8601 UTC
  latest_month        'YYYY-MM' of the last month with a YoY for every scheme
  diary_years         [int]     CE Diary years used for frequency
  weight_years        [int]     December relative-importance years used for chaining
  labels              {scheme: user-facing label}
  method              {bill_frequency_per_cuweek, bill_items:[{item_code,item_name}], multi_eli_split, ...}
  bootstrap           {replicates, formula, source, missing:{diary_year: n}}
  series              [{ym, published_yoy, official_replica_yoy,
                        salience_yoy, salience_se, blend50_yoy,
                        bill_salience_yoy, bill_salience_se, bill_blend50_yoy}]
                      *_se are BRR standard errors of the gap vs official_replica, in pp.
  sensitivity         [{variant, ym, yoy}]  full monthly series for each robustness variant
  sensitivity_latest  [{variant, yoy, gap}] latest_month only, gap = yoy - official replica yoy
  sensitivity_range   {ym, min_gap, max_gap, range_pp}
  items_latest        [{item_code, name, w_exp, w_sal, w_bill, yoy, contrib_exp, contrib_sal, gap_driver}]
  notes               [str]
"""
import sys, json, zipfile, re, math
import pandas as pd, numpy as np
from common import *

CE_CSV = "https://www.bls.gov/cex/pumd/data/csv/diary{yy}.zip"      # 2022+
CE_CSV_OLD = "https://www.bls.gov/cex/pumd/data/comma/diary{yy}.zip"  # <=2021
CONC = "https://www.bls.gov/cpi/additional-resources/ce-cpi-concordance.xlsx"
RI_ARCHIVE = "https://www.bls.gov/cpi/tables/relative-importance/ri-archive-2010-2019.zip"

NREP = 44          # CE PUMD replicate weights WTREP01..WTREP44
EXTEND_YEARS = [2017, 2018, 2019]
GEN_MARK = "<!-- generated by p1_salience.extend_weights from the BLS RI text archive -->"

# ---------------------------------------------------------------------------
# Bill-salience variant.
#
# The Diary records *purchase entries* over a two-week window, so recurring bills that are
# paid by standing order and are collected by the Interview survey (rent, OER, insurance,
# tuition, utilities...) get essentially zero purchase-entry frequency even though a household
# meets them every single month.  The `bill_salience` variant gives every item below a floor
# of one entry per month = 1/4.345 entries per CU-week (4.345 = 52.14/12 weeks per month),
# *unless* the Diary already observes it more often, in which case the Diary value wins.
# Everything else is untouched.  This is a deliberately crude "you see this bill once a month"
# assumption, not an estimate of anything BLS publishes.
#
# Excluded on purpose: SEHB02 (hotels - not a recurring bill), SERA04 "Purchase, subscription,
# and rental of video" and SERA06 "Recorded music and music subscriptions" (mix subscriptions
# with one-off purchases/rentals), SETF03 "Parking and other fees" (transactional, and the
# Diary already sees it), SEMD01/SEMC01 medical services (episodic, not a monthly bill).
BILL_FREQ = 1.0 / 4.345
BILL_ITEMS = {
    "SEHA":   "Rent of primary residence",
    "SEHC01": "Owners' equivalent rent of primary residence",
    "SEHD":   "Tenants' and household insurance",
    "SETE":   "Motor vehicle insurance",
    "SEME":   "Health insurance",
    "SEHF01": "Electricity",
    "SEHF02": "Utility (piped) gas service",
    "SEHG01": "Water and sewerage maintenance",
    "SEHG02": "Garbage and trash collection",
    "SEED03": "Wireless telephone services",
    "SEED04": "Residential telephone services",
    "SEEE03": "Internet services and electronic information providers",
    "SERA02": "Cable, satellite, and live streaming television service",
    "SEEB01": "College tuition and fees",
    "SEEB02": "Elementary and high school tuition and fees",
    "SEEB03": "Day care and preschool",
    "SETF01": "State motor vehicle registration and license fees",
}

SCHEMA1 = """
CREATE TABLE IF NOT EXISTS p1_ucc_freq(diary_year INT, ucc TEXT, entries_per_cuweek REAL, spend_per_cuweek REAL, share_buying REAL, PRIMARY KEY(diary_year, ucc));
CREATE TABLE IF NOT EXISTS p1_item_salience(diary_year INT, item_code TEXT, freq REAL, w_sal REAL, w_exp REAL, PRIMARY KEY(diary_year, item_code));
CREATE TABLE IF NOT EXISTS p1_index(scheme TEXT, ym TEXT, idx REAL, yoy REAL, PRIMARY KEY(scheme, ym));
CREATE TABLE IF NOT EXISTS p1_sensitivity(variant TEXT, ym TEXT, yoy REAL, PRIMARY KEY(variant, ym));
CREATE TABLE IF NOT EXISTS p1_boot(scheme TEXT, ym TEXT, yoy REAL, se REAL, PRIMARY KEY(scheme, ym));
"""


# ---------------------------------------------------------------------------
# CE Diary micro data
# ---------------------------------------------------------------------------
class DiaryYear:
    """One CE Diary year, kept in a form that makes replicate re-weighting cheap.

    entries(col) returns weighted purchase entries per CU-week by UCC, where col 0 is the
    final weight FINLWT21 and cols 1..44 are the BRR replicate weights WTREP01..WTREP44.
    """

    def __init__(self, yy):
        d = RAW / "ce" / f"diary{yy}"
        if not d.exists():
            url = (CE_CSV if int(yy) >= 22 else CE_CSV_OLD).format(yy=yy)
            z, _ = fetch(url, RAW / "ce" / f"diary{yy}.zip")
            zipfile.ZipFile(z).extractall(RAW / "ce")
        self.year = 2000 + int(yy)
        exp = pd.concat([pd.read_csv(f, dtype={"NEWID": str, "UCC": str}, usecols=["NEWID", "UCC", "COST", "ALLOC"])
                         for f in sorted(d.glob("expd*.csv"))])
        head = pd.read_csv(sorted(d.glob("fmld*.csv"))[0], nrows=0)
        rep = [f"WTREP{i:02d}" for i in range(1, NREP + 1)]
        self.have_rep = [c for c in rep if c in head.columns]
        self.missing_rep = [c for c in rep if c not in head.columns]
        fml = pd.concat([pd.read_csv(f, dtype={"NEWID": str}, usecols=["NEWID", "FINLWT21"] + self.have_rep)
                         for f in sorted(d.glob("fmld*.csv"))])
        fml = fml.drop_duplicates("NEWID").reset_index(drop=True)

        # WTREP is blank for CUs not assigned to that half-sample -> weight 0 (BLS PUMD guide, sec. 6.3)
        self.Wm = np.zeros((len(fml), NREP + 1))
        self.Wm[:, 0] = pd.to_numeric(fml.FINLWT21, errors="coerce").fillna(0.0).values
        self.na_rep = 0
        for i, c in enumerate(rep, start=1):
            if c in self.have_rep:
                v = pd.to_numeric(fml[c], errors="coerce")
                self.na_rep += int(v.isna().sum())
                self.Wm[:, i] = v.fillna(0.0).values
            else:
                self.Wm[:, i] = self.Wm[:, 0]      # no replicate -> contributes no variance
        self.W = self.Wm[:, 0].sum()
        self.colsum = self.Wm.sum(axis=0)

        row_of = pd.Series(np.arange(len(fml)), index=fml.NEWID.values)
        exp = exp.assign(row=exp.NEWID.map(row_of)).dropna(subset=["row"])
        exp["row"] = exp.row.astype(int)
        pairs = exp.groupby(["UCC", "row"], sort=True).size().reset_index(name="n")
        self.ucc, self.uidx = np.unique(pairs.UCC.values, return_inverse=True)
        self.rows = pairs.row.values
        self.cnt = pairs.n.values.astype(float)

        idx = pd.Index(self.ucc, name="ucc")
        w = self.Wm[self.rows, 0]
        self.freq = pd.DataFrame({
            "entries_per_cuweek": self.entries(0).values,
            "spend_per_cuweek": ((exp.COST * self.Wm[exp.row.values, 0]).groupby(exp.UCC).sum() / self.W).reindex(idx).fillna(0.0).values,
            "share_buying": np.bincount(self.uidx, weights=w, minlength=len(self.ucc)) / self.W,
        }, index=idx).reset_index()
        self.freq["diary_year"] = self.year
        log.info("diary %s: %d CU-weeks (sum FINLWT21 %.3g), %d expd rows, %d UCCs, %d replicate cols (%d blank cells -> 0)",
                 yy, len(fml), self.W, len(exp), len(self.ucc), len(self.have_rep), self.na_rep)
        if self.missing_rep:
            log.warning("diary %s: MISSING replicate columns %s - those replicates reuse FINLWT21 (no variance contribution)",
                        yy, self.missing_rep)

    def entries(self, col):
        w = self.Wm[:, col]
        tot = self.colsum[col]
        if tot <= 0:
            return pd.Series(0.0, index=self.ucc)
        v = self.cnt * w[self.rows]
        return pd.Series(np.bincount(self.uidx, weights=v, minlength=len(self.ucc)) / tot, index=self.ucc)


def concordance():
    p, _ = fetch(CONC, RAW / "ce" / "ce-cpi-concordance.xlsx")
    df = pd.read_excel(p, header=None, dtype=str)
    hdr = df.index[df[0].str.strip().str.upper().eq("UCC")][0]
    df = df.iloc[hdr + 1:, :5]
    df.columns = ["ucc", "eli", "ucc_title", "eli_title", "source"]
    df = df.dropna(subset=["ucc", "eli"])
    df = df[df.ucc.str.match(r"^\d{6}$")]
    df["ucc"] = df.ucc.str.strip(); df["eli"] = df.eli.str.strip().str.upper()
    return df


def map_eli_to_leaf(eli, leaf_set, item_codes=None):
    """ELI 'FA011' -> stratum 'SEFA01' -> published leaf; walk up if not published."""
    for k in (4, 3, 2):
        c = "SE" + eli[:k]
        if c in leaf_set:
            return c
    return None


# ---------------------------------------------------------------------------
# UCC -> leaf item linear operators
# ---------------------------------------------------------------------------
def ucc_item_matrix(conc, leaf, split="exp"):
    """A[i,j] = share of UCC j's purchase entries assigned to leaf item i.

    29 UCCs fan out to several ELIs.  split='exp' apportions them by the target items'
    expenditure weight (proxy for BLS's unpublished special adjustment factors);
    split='equal' gives each mapped target an equal share.  A UCC whose targets all have
    zero/absent expenditure weight falls back to an equal split either way.
    """
    leaf_set = set(leaf.index)
    m = conc[["ucc", "eli"]].copy()
    m["item_code"] = m.eli.map(lambda e: map_eli_to_leaf(e, leaf_set))
    if split == "exp":
        m["wt"] = m.item_code.map(leaf).fillna(0.0)
    else:
        m["wt"] = m.item_code.notna().astype(float)
    m["wt"] = m.wt.where(m.groupby("ucc").wt.transform("sum") > 0, 1.0)
    m["share"] = m.wt / m.groupby("ucc").wt.transform("sum")
    uccs = np.array(sorted(m.ucc.unique()))
    ui = {u: j for j, u in enumerate(uccs)}
    items = list(leaf.index)
    ii = {c: i for i, c in enumerate(items)}
    A = np.zeros((len(items), len(uccs)))
    for r in m.dropna(subset=["item_code"]).itertuples():
        A[ii[r.item_code], ui[r.ucc]] += r.share
    return uccs, A


def class_operator(leaf):
    """C: aggregate leaf frequency to the expenditure class (item_code[:4], e.g. SEFA) and
    spread it back over that class's leaves in proportion to expenditure weight."""
    items = list(leaf.index)
    key = np.array([c[:4] for c in items])
    same = (key[:, None] == key[None, :]).astype(float)
    tot = same @ leaf.values
    sh = np.where(tot > 0, leaf.values / np.where(tot > 0, tot, 1.0), 1.0 / same.sum(axis=1))
    return same * sh[:, None]


# ---------------------------------------------------------------------------
# December-chained Laspeyres
# ---------------------------------------------------------------------------
MIN_COV = 0.90     # a month is only priced if >= this share of the scheme's leaf weight has data


class Chainer:
    """Vectorised December-chained Laspeyres; arithmetic identical to dec_chained().

    A month is skipped unless leaves carrying at least MIN_COV of the scheme's total weight
    have both a December base index and a current index.  Without this, October 2025 (no CPI
    release - government shutdown) was priced off the ~11 leaf items that happen to carry an
    Oct-2025 observation, which produced a spurious index level and YoY.
    """

    def __init__(self, im, leaves_by_year, pub_sa0):
        self.pub = pub_sa0
        self.skipped = {}
        self.years = sorted(leaves_by_year)
        piv = im.pivot_table(index="item_code", columns="ym", values="idx_nsa")
        self.items, self.months, self.R, self.M = {}, {}, {}, {}
        for y in self.years:
            items = list(leaves_by_year[y])
            self.items[y] = items
            bym = f"{y}-12"
            b = piv[bym].reindex(items).values if bym in piv.columns else np.full(len(items), np.nan)
            ms, rows = [], []
            for mo in range(1, 13):
                ym = f"{y+1}-{mo:02d}"
                if ym not in piv.columns:
                    continue
                ms.append(ym)
                rows.append(piv[ym].reindex(items).values / b)
            R = np.array(rows) if rows else np.zeros((0, len(items)))
            self.months[y] = ms
            self.M[y] = np.isfinite(R).astype(float)
            self.R[y] = np.where(np.isfinite(R), R, 0.0)

    def run(self, weights_by_year, note=None):
        out, skipped = {}, []
        for y in self.years:
            if y not in weights_by_year or not self.months[y]:
                continue
            w = pd.Series(weights_by_year[y]).reindex(self.items[y]).fillna(0.0).values.astype(float)
            tot = w.sum()
            if tot <= 0:
                continue
            den = self.M[y] @ w
            num = self.R[y] @ w
            for k, ym in enumerate(self.months[y]):
                if den[k] >= MIN_COV * tot:
                    out[ym] = num[k] / den[k]
                elif den[k] > 0:
                    skipped.append((ym, den[k] / tot))
        for ym, c in skipped:
            self.skipped[ym] = max(self.skipped.get(ym, 0.0), c)
        if note and skipped:
            log.info("%s: dropped %d month(s) with leaf coverage < %.0f%%: %s", note, len(skipped), MIN_COV * 100,
                     [(ym, f"{100*c:.1f}%") for ym, c in skipped])
        s = pd.Series(out).sort_index()
        level, last_dec = {}, None
        for ym, rel in s.items():
            y = int(ym[:4]) - 1
            if last_dec is None or last_dec[0] != y:
                last_dec = (y, level.get(f"{y}-12", self.pub.get(f"{y}-12")))
            level[ym] = last_dec[1] * rel
        lv = pd.Series(level).sort_index()
        p = pd.PeriodIndex(lv.index, freq="M")
        prev = pd.Series(lv.values, index=(p + 12).astype(str))
        yoy = (lv / prev.reindex(lv.index) - 1) * 100
        return lv, yoy


def dec_chained(im, weights_by_year, pub_sa0):
    """Dec-chained Laspeyres over leaves. weights_by_year: {weight_year: Series(item_code -> weight)}.
    Kept as a module-level entry point (it is the comparison standard).
    Months with less than MIN_COV of the leaf weight priced are dropped, not extrapolated."""
    return Chainer(im, {y: list(w.index) for y, w in weights_by_year.items()}, pub_sa0).run(weights_by_year)


# ---------------------------------------------------------------------------
# Back-fill Dec-2017..2019 relative importance from the BLS text archive
# ---------------------------------------------------------------------------
NUM_RE = re.compile(r"(?<![\d.])((?:\d{1,3}(?:,\d{3})*)?\.\d+)(?![\d.])")

# CPI item titles that changed between the 2017-2019 relative-importance tables and today's
# cu.item file.  p0_fetch.load_weights matches rows to item codes by *name*, so the archived
# names are rewritten to the current ones here (in our staged HTML) rather than by touching p0.
RI_RENAME = {
    "cable and satellite television service": "Cable, satellite, and live streaming television service",
    "child care and nursery school": "Day care and preschool",
    "land line telephone services": "Residential telephone services",
    "personal computers and peripheral equipment": "Computers, peripherals, and smart home assistants",
    "computers peripherals and smart home assistant devices": "Computers, peripherals, and smart home assistants",
    "women s underwear nightwear sportswear and accessories": "Women's underwear, nightwear, swimwear and accessories",
    "men s furnishings": "Men's underwear, nightwear, swimwear and accessories",
    "housing at school excluding board": "Lodging while at school",
    "care of invalids and elderly at home": "Home health care",
    "video discs and other media including rental of video": "Purchase, subscription, and rental of video",
    "other pork including roasts and picnics": "Other pork including roasts, steaks, and ribs",
    "other poultry including turkey": "Other uncooked poultry including turkey",
    "baby food": "Baby food and formula",
    "sugar and artificial sweeteners": "Sugar and sugar substitutes",
    "photographers and film processing": "Photographers and photo processing",
    "technical and business school tuition and fees": "Technical and vocational school tuition and fixed fees",
}


def _nkey(s):
    s = re.sub(r"\(\d+\)", "", s).lower()
    return re.sub(r"\s+", " ", re.sub(r"[^a-z0-9 ]", " ", s)).strip()


def ri_txt_to_html(txt):
    """Fixed-width RI table (BLS ri-archive *.txt) -> the minimal HTML p0_fetch.load_weights parses.

    Item names use dot leaders and may wrap over 2-3 lines (the wrapped tail is indented
    further than the head of the entry); values are 'nn.nnn' or '.nnn' (CPI-U then CPI-W).
    """
    rows, pend = [], []
    for raw in txt.replace("\r", "").split("\n"):
        line = raw.rstrip()
        if not line.strip():
            pend = []
            continue
        ind = len(line) - len(line.lstrip())
        if "special aggregate" in line.lower():
            rows.append("<tr><td>Special aggregate indexes</td></tr>")
            pend = []
            continue
        nums = list(NUM_RE.finditer(line))
        if len(nums) >= 2:
            name = line[:nums[-2].start()].rstrip(" .").strip()
            if pend and ind > pend[0][0]:                 # deeper than the head of the entry
                name = " ".join(t for _, t in pend) + " " + name
            pend = []
            if not name:
                continue
            name = RI_RENAME.get(_nkey(name), name)
            rows.append(f"<tr><th>{name}</th><td>{nums[-2].group(1)}</td><td>{nums[-1].group(1)}</td></tr>")
        else:
            pend = (pend + [(ind, line.strip())])[-3:]
    return GEN_MARK + "\n<table>\n" + "\n".join(rows) + "\n</table>\n"


def extend_weights(con, years=EXTEND_YEARS, force=False):
    """Stage archived December relative-importance tables as HTML, then hand them to
    p0_fetch.load_weights *unmodified* so the name->code matching, level and leaf logic is
    byte-identical to the 2020+ weights.  Returns the list of years actually loaded."""
    have = {r[0] for r in con.execute("SELECT DISTINCT weight_year FROM cpi_weight").fetchall()}
    todo = [y for y in years if force or y not in have]
    if not todo:
        log.info("weight back-fill: %s already present", years)
        return []
    try:
        import p0_fetch
    except Exception as e:
        log.warning("weight back-fill skipped: cannot import p0_fetch (%s)", e)
        return []
    try:
        z, _ = fetch(RI_ARCHIVE, RAW / "weights" / "ri-archive-2010-2019.zip")
        zf = zipfile.ZipFile(z)
        names = {n.rsplit("/", 1)[-1]: n for n in zf.namelist()}
        staged = []
        for y in todo:
            src = names.get(f"{y}.txt")
            if not src:
                log.warning("weight back-fill: %d.txt not in %s", y, RI_ARCHIVE)
                continue
            dest = RAW / "weights" / f"{y}.htm"
            if dest.exists() and GEN_MARK not in dest.read_text(encoding="utf-8", errors="ignore"):
                log.warning("weight back-fill: %s exists and was not generated by us - leaving it alone", dest)
            else:
                dest.parent.mkdir(parents=True, exist_ok=True)
                dest.write_text(ri_txt_to_html(zf.read(src).decode("latin-1")), encoding="utf-8")
            staged.append(y)
        if not staged:
            return []
        orig = p0_fetch.fetch

        def local_first(url, d, **kw):          # serve the staged file; the live URL 404s
            return (d, True) if d.exists() else orig(url, d, **kw)
        p0_fetch.fetch = local_first
        try:
            p0_fetch.load_weights(con, years=staged)
        finally:
            p0_fetch.fetch = orig
        got = [y for y in staged if con.execute("SELECT 1 FROM cpi_weight WHERE weight_year=? LIMIT 1", (y,)).fetchone()]
        log.info("weight back-fill: loaded %s from the BLS RI text archive", got)
        return got
    except Exception as e:
        log.warning("weight back-fill FAILED (%s) - continuing with 2020+ weights only", e)
        return []


# ---------------------------------------------------------------------------
def main(years, do_boot=True, do_extend=True, force_extend=False):
    con = init_db(); con.executescript(SCHEMA1); con.commit()
    if do_extend:
        extend_weights(con, force=force_extend)

    im = pd.read_sql("SELECT item_code, ym, idx_nsa FROM cpi_item_month", con)
    names = pd.read_sql("SELECT item_code, item_name FROM cu_item", con).set_index("item_code").item_name
    wexp = pd.read_sql("SELECT weight_year, item_code, weight_u FROM cpi_weight WHERE is_leaf=1 AND matched=1", con)
    pub = im[im.item_code == "SA0"].set_index("ym").idx_nsa
    conc = concordance()
    log.info("concordance: %d rows, %d UCCs (%d flagged Diary-source), %d UCCs fan out to >1 ELI",
             len(conc), conc.ucc.nunique(), conc[conc.source.str.upper().str.startswith("D")].ucc.nunique(),
             int((conc.groupby("ucc").eli.nunique() > 1).sum()))

    # ---- diary micro data -------------------------------------------------
    dys = {}
    for yy in years:
        o = DiaryYear(yy)
        dys[o.year] = o
        con.execute("DELETE FROM p1_ucc_freq WHERE diary_year=?", (o.year,))
        con.executemany("INSERT INTO p1_ucc_freq VALUES(?,?,?,?,?)",
                        o.freq[["diary_year", "ucc", "entries_per_cuweek", "spend_per_cuweek", "share_buying"]].values.tolist())
    con.commit()
    avail = sorted(dys)
    base_ent = {dy: dys[dy].entries(0) for dy in avail}
    totW = sum(dys[dy].W for dy in avail)
    pooled_ent = (pd.concat([base_ent[dy] * dys[dy].W for dy in avail], axis=1).fillna(0.0).sum(axis=1) / totW)

    def pick(wy):
        le = [a for a in avail if a <= wy]
        return wy if wy in avail else (max(le) if le else avail[0])

    # ---- per weight-year operators ---------------------------------------
    wyears = sorted(int(y) for y in wexp.weight_year.unique())
    leaf_by = {wy: wexp[wexp.weight_year == wy].set_index("item_code").weight_u for wy in wyears}
    maps = {(wy, sp): ucc_item_matrix(conc, leaf_by[wy], sp) for wy in wyears for sp in ("exp", "equal")}
    cops = {wy: class_operator(leaf_by[wy]) for wy in wyears}
    billmask = {wy: np.array([c in BILL_ITEMS for c in leaf_by[wy].index]) for wy in wyears}
    ch = Chainer(im, {wy: list(leaf_by[wy].index) for wy in wyears}, pub)
    log.info("weight years %s (leaves %s)", wyears, [len(leaf_by[w]) for w in wyears])

    # coverage diagnostics on the newest weight year
    top = max(wyears)
    fy = base_ent[pick(top)]
    known = set(conc.ucc)
    nomap = fy[~fy.index.isin(known)]
    log.info("diary UCCs with no concordance row: %d (%.1f%% of entries): %s",
             len(nomap), 100 * nomap.sum() / fy.sum(), nomap.sort_values(ascending=False).head(12).index.tolist())
    _, A_top = maps[(top, "exp")]
    e_top = fy.reindex(maps[(top, "exp")][0]).fillna(0.0).values
    log.info("weight year %d: %.1f%% of concordance-mapped entry mass lands on a published leaf", top,
             100 * (A_top @ e_top).sum() / max(e_top.sum(), 1e-12))

    def weights_for(ent_fn, split="exp", agg="item", bills=False):
        out = {}
        for wy in wyears:
            uccs, A = maps[(wy, split)]
            f = A @ ent_fn(wy).reindex(uccs).fillna(0.0).values
            if agg == "class":
                f = cops[wy] @ f
            if bills:
                f = np.where(billmask[wy], np.maximum(f, BILL_FREQ), f)
            s = f.sum()
            out[wy] = pd.Series(f / s * 100 if s > 0 else f, index=leaf_by[wy].index)
        return out

    base_fn = lambda wy: base_ent[pick(wy)]
    w_off = {wy: leaf_by[wy] / leaf_by[wy].sum() * 100 for wy in wyears}
    w_frq = weights_for(base_fn)
    w_bil = weights_for(base_fn, bills=True)
    blend = lambda a: {wy: 0.5 * w_off[wy] + 0.5 * a[wy] for wy in wyears}

    schemes = {"official_replica": w_off, "salience": w_frq, "blend50": blend(w_frq),
               "bill_salience": w_bil, "bill_blend50": blend(w_bil)}
    res = {}
    for name, wb in schemes.items():
        lv, yoy = ch.run(wb, note=f"scheme {name}")
        res[name] = (lv, yoy)
        con.execute("DELETE FROM p1_index WHERE scheme=?", (name,))
        con.executemany("INSERT INTO p1_index VALUES(?,?,?,?)",
                        [(name, ym, float(lv[ym]), None if pd.isna(yoy[ym]) else float(yoy[ym])) for ym in lv.index])
    con.commit()

    item_rows = []
    for wy in wyears:
        dy = pick(wy)
        uccs, A = maps[(wy, "exp")]
        f = A @ base_ent[dy].reindex(uccs).fillna(0.0).values
        for i, c in enumerate(leaf_by[wy].index):
            item_rows.append((dy, c, float(f[i]), float(w_frq[wy][c]), float(w_off[wy][c])))
        log.info("weight year %d (diary %d): %d leaves, %d with frequency>0, top frequency weights: %s",
                 wy, dy, len(leaf_by[wy]), int((w_frq[wy] > 0).sum()),
                 [(names.get(c, c)[:28], round(v, 2)) for c, v in w_frq[wy].sort_values(ascending=False).head(6).items()])
    con.execute("DELETE FROM p1_item_salience")
    con.executemany("INSERT OR REPLACE INTO p1_item_salience VALUES(?,?,?,?,?)", item_rows)
    con.commit()

    # ---- sensitivity trio -------------------------------------------------
    variants = {
        "split_exp":    weights_for(base_fn, split="exp"),      # = headline
        "split_equal":  weights_for(base_fn, split="equal"),
        "agg_item":     w_frq,                                  # = headline
        "agg_class":    weights_for(base_fn, agg="class"),
        "diary_pooled": weights_for(lambda wy: pooled_ent),
    }
    for dy in avail:
        variants[f"diary_{dy}"] = weights_for(lambda wy, d=dy: base_ent[d])
    sens = {}
    con.execute("DELETE FROM p1_sensitivity")
    for v, wb in variants.items():
        _, yoy = ch.run(wb, note=f"variant {v}")
        sens[v] = yoy
        con.executemany("INSERT INTO p1_sensitivity VALUES(?,?,?)",
                        [(v, ym, None if pd.isna(yoy[ym]) else float(yoy[ym])) for ym in yoy.index])
    con.commit()

    yoy_off = res["official_replica"][1]
    months = [ym for ym in res["salience"][1].index if not pd.isna(res["salience"][1][ym]) and not pd.isna(yoy_off.get(ym, np.nan))]
    latest = months[-1]
    gaps = {v: float(sens[v][latest] - yoy_off[latest]) for v in variants}
    lo, hi = min(gaps.values()), max(gaps.values())
    log.info("SENSITIVITY %s: gap (variant YoY - official replica YoY) across %d variants: min %+.3f max %+.3f, RANGE %.3f pp",
             latest, len(gaps), lo, hi, hi - lo)
    for v in sorted(gaps, key=gaps.get):
        log.info("   %-14s yoy %.3f  gap %+.3f", v, sens[v][latest], gaps[v])

    # ---- BRR bootstrap ----------------------------------------------------
    # BLS CE PUMD, "Getting Started Guide" sec. 6.3 (bls.gov/cex/pumd-getting-started-guide.htm):
    #     sigma = sqrt( sum_{WTREP=1..44} (X_WTREP - X)^2 / 44 )
    # i.e. variance = (1/44) * sum (theta_r - theta)^2.  The PUMD replicate weights are already
    # doubled half-sample weights (median WTREP/FINLWT21 = 2.00, sum WTREP_r = sum FINLWT21), so
    # no Fay factor is applied.  Under the Fay k=0.5 convention (variance = (4/44)*sum) every SE
    # below would be exactly 2x larger.
    boot = {}
    if do_boot:
        bschemes = {"salience": dict(bills=False), "bill_salience": dict(bills=True)}
        acc = {s: [] for s in bschemes}
        blend_acc = {"blend50": [], "bill_blend50": []}
        for r in range(1, NREP + 1):
            ent_r = {dy: dys[dy].entries(r) for dy in avail}
            fn = lambda wy: ent_r[pick(wy)]
            for s, kw in bschemes.items():
                wb = weights_for(fn, **kw)
                acc[s].append(ch.run(wb)[1])
                blend_acc["blend50" if s == "salience" else "bill_blend50"].append(ch.run(blend(wb))[1])
            if r % 11 == 0:
                log.info("bootstrap replicate %d/%d", r, NREP)
        for s, full in (("salience", res["salience"][1]), ("bill_salience", res["bill_salience"][1]),
                        ("blend50", res["blend50"][1]), ("bill_blend50", res["bill_blend50"][1])):
            reps = acc[s] if s in acc else blend_acc[s]
            gap0 = full - yoy_off
            D = pd.concat([(y - yoy_off) - gap0 for y in reps], axis=1)
            se = np.sqrt((D ** 2).sum(axis=1) / NREP).where(gap0.notna())
            boot[s] = se
            con.execute("DELETE FROM p1_boot WHERE scheme=?", (s,))
            con.executemany("INSERT INTO p1_boot VALUES(?,?,?,?)",
                            [(s, ym, None if pd.isna(full.get(ym, np.nan)) else float(full[ym]),
                              None if pd.isna(se.get(ym, np.nan)) else float(se[ym])) for ym in full.index])
        con.commit()
        log.info("bootstrap: %s", ", ".join(f"{s} {latest} gap {float(res[s][1][latest]-yoy_off[latest]):+.3f} +/- {float(boot[s][latest]):.3f} pp"
                                            for s in ("salience", "bill_salience")))

    # ---- validation of the replica against published ----------------------
    p = pd.PeriodIndex(pub.index, freq="M")
    pub_yoy = (pub / pd.Series(pub.values, index=(p + 12).astype(str)).reindex(pub.index) - 1) * 100
    d = (res["official_replica"][1] - pub_yoy.reindex(res["official_replica"][1].index)).dropna()
    log.info("official_replica vs published YoY: n=%d %s..%s, mean %+.3f, max|diff| %.3f pp",
             len(d), d.index[0], d.index[-1], d.mean(), d.abs().max())
    for yr in sorted({ym[:4] for ym in d.index}):
        dd = d[[i for i in d.index if i.startswith(yr)]]
        log.info("   %s: mean %+.3f max|diff| %.3f", yr, dd.mean(), dd.abs().max())

    # ---- JSON -------------------------------------------------------------
    latest_wy = int(latest[:4]) - 1
    prev_ym = f"{latest_wy}-{latest[5:]}"
    tbl = pd.DataFrame({
        "w_exp": w_off[latest_wy], "w_sal": w_frq[latest_wy], "w_bill": w_bil[latest_wy],
        "yoy": im[im.ym == latest].set_index("item_code").idx_nsa / im[im.ym == prev_ym].set_index("item_code").idx_nsa * 100 - 100,
    }).dropna()
    tbl["name"] = tbl.index.map(lambda c: names.get(c, c))
    tbl["contrib_exp"] = tbl.w_exp * tbl.yoy / 100
    tbl["contrib_sal"] = tbl.w_sal * tbl.yoy / 100
    tbl["gap_driver"] = tbl.contrib_sal - tbl.contrib_exp

    def g(s, ym):
        v = s.get(ym, np.nan)
        return None if pd.isna(v) else round(float(v), 3)

    out = {
        "generated_at": pd.Timestamp.now("UTC").isoformat(),
        "latest_month": latest,
        "diary_years": avail,
        "weight_years": wyears,
        "labels": {"official_replica": "Official (expenditure-weighted) replica",
                   "salience": "Frequency-weighted CPI",
                   "blend50": "50/50 expenditure + frequency",
                   "bill_salience": "Bill-adjusted frequency-weighted CPI",
                   "bill_blend50": "50/50 expenditure + bill-adjusted frequency"},
        "method": {
            "frequency": "share of weighted CE Diary purchase entries per consumer-unit-week, mapped UCC -> ELI -> published item stratum",
            "multi_eli_split": "expenditure-weight split of the 29 multi-ELI UCCs (see sensitivity variant split_equal)",
            "aggregation_level": "published item (see sensitivity variant agg_class)",
            "bill_frequency_per_cuweek": round(BILL_FREQ, 6),
            "bill_rule": "max(diary frequency, 1/4.345 entries per CU-week) for the listed items only",
            "bill_items": [{"item_code": c, "item_name": names.get(c, n)} for c, n in sorted(BILL_ITEMS.items())],
            "index": "December-chained Laspeyres over the same leaf universe as the P0 replica",
            "min_leaf_coverage": MIN_COV,
            "excluded_months": {ym: round(100 * c, 1) for ym, c in sorted(ch.skipped.items())},
        },
        "bootstrap": {
            "replicates": NREP,
            "formula": "sigma = sqrt( sum_{r=1..44} (theta_r - theta)^2 / 44 )",
            "source": "BLS CE PUMD Getting Started Guide sec. 6.3 'Estimating sampling error' (https://www.bls.gov/cex/pumd-getting-started-guide.htm)",
            "quantity": "standard error of (scheme YoY - official replica YoY), percentage points",
            "note": "PUMD replicate weights are doubled half-sample weights, so no Fay factor is applied; under the Fay k=0.5 convention (variance = 4/44 * sum) every SE would be exactly 2x larger.",
            "blank_replicate_cells": {str(dy): int(dys[dy].na_rep) for dy in avail},
            "missing_replicate_columns": {str(dy): dys[dy].missing_rep for dy in avail},
        },
        "series": [{"ym": ym,
                    "published_yoy": g(pub_yoy, ym),
                    "official_replica_yoy": g(yoy_off, ym),
                    "salience_yoy": g(res["salience"][1], ym),
                    "salience_se": g(boot["salience"], ym) if "salience" in boot else None,
                    "blend50_yoy": g(res["blend50"][1], ym),
                    "blend50_se": g(boot["blend50"], ym) if "blend50" in boot else None,
                    "bill_salience_yoy": g(res["bill_salience"][1], ym),
                    "bill_salience_se": g(boot["bill_salience"], ym) if "bill_salience" in boot else None,
                    "bill_blend50_yoy": g(res["bill_blend50"][1], ym),
                    "bill_blend50_se": g(boot["bill_blend50"], ym) if "bill_blend50" in boot else None}
                   for ym in months],
        "sensitivity": [{"variant": v, "ym": ym, "yoy": g(sens[v], ym)} for v in sorted(sens) for ym in months],
        "sensitivity_latest": [{"variant": v, "yoy": round(float(sens[v][latest]), 3), "gap": round(gaps[v], 3)}
                               for v in sorted(gaps, key=gaps.get)],
        "sensitivity_range": {"ym": latest, "min_gap": round(lo, 3), "max_gap": round(hi, 3), "range_pp": round(hi - lo, 3)},
        "items_latest": tbl.sort_values("w_sal", ascending=False).round(3).reset_index().rename(columns={"index": "item_code"}).to_dict(orient="records"),
        "notes": [
            "'Frequency-weighted' means each published CPI item is weighted by how often households record buying it in the CE Diary, not by how much they spend. Table and column names keep the older word 'salience' for compatibility.",
            "The Diary is a two-week purchase log, so recurring bills collected by the CE Interview survey (rent, owners' equivalent rent, insurance, tuition, most medical care) score near zero frequency by construction. The bill_salience variant puts a one-entry-per-month floor under a documented list of such items; it is an assumption, not a measurement.",
            "Purchase-entry counts also reflect how finely BLS splits an item into UCCs: an item recorded as several UCCs accumulates more entries than an equally common item recorded as one. The agg_class sensitivity variant aggregates frequency at the expenditure-class level to show how much that matters.",
            "All indexes are December-chained Laspeyres over the same leaf universe; official_replica tracks the published all-items NSA YoY closely (see log for the year-by-year diff).",
            f"A month is only priced when leaves carrying at least {MIN_COV:.0%} of the scheme's weight have data, so October 2025 (no CPI release) is absent from every scheme rather than being priced off the handful of items that happen to have an observation.",
            "Descriptive only - no causal claim that any of these indexes measures inflation as experienced or perceived.",
        ],
    }
    (OUT / "p1_salience.json").write_text(json.dumps(out, indent=1, allow_nan=False))

    def line(ym):
        s = f"{ym}: published {g(pub_yoy,ym)} | replica {g(yoy_off,ym)} | frequency {g(res['salience'][1],ym)}"
        if "salience" in boot:
            s += f" (SE {g(boot['salience'],ym)})"
        s += f" | blend50 {g(res['blend50'][1],ym)} | bill {g(res['bill_salience'][1],ym)}"
        if "bill_salience" in boot:
            s += f" (SE {g(boot['bill_salience'],ym)})"
        return s + f" | bill_blend50 {g(res['bill_blend50'][1],ym)}"

    for ym in (latest, "2022-06", "2024-06", "2019-06", "2020-06"):
        if ym in months:
            log.info("=== %s", line(ym))
    log.info("biggest gap drivers (frequency minus expenditure contribution, pp): %s",
             [(r.name[:30], round(r.gap_driver, 2)) for r in tbl.sort_values("gap_driver", key=abs, ascending=False).head(8).itertuples()])


if __name__ == "__main__":
    if "--help" in sys.argv or "-h" in sys.argv:
        print(__doc__); sys.exit(0)
    years, boot, ext, fext = ["22", "23", "24"], True, True, False
    for a in sys.argv[1:]:
        if a.startswith("--years"):
            years = a.split("=")[1].split(",")
        elif a == "--no-boot":
            boot = False
        elif a == "--no-extend":
            ext = False
        elif a == "--force-extend":
            fext = True
    main(years, do_boot=boot, do_extend=ext, force_extend=fext)
